### ISSUE TITLE
Почему это рогалик?

### ISSUE THREAD

**Issue by SID37** [TRCMKR/Kingdom-of-Nerds#84]
В игре перманентная смерть, но не ясно зачем. В рогаликах это компенсируется генерацией контента, то есть каждое прохождение уникальное. Тут игра состоит из неменяющихся уровней, перманентная смерть вызывает только раздражение от того, что надо заново доходить до того же уровня.

**Comment by TRCMKR** [comment]
Мы не позиционировали себя как рогалик (Rogue-like), вместо этого мы придерживаемся Rogue-lite, что позволяет нам соблюдать не все правила жанра. Хорошим примером этого является игра Hades, с которой мы брали принципы работы уровней и локаций. Например, у них есть 3 локации, в каждой из них свой заготовленный сет уровней, каждый забег вам «выпадает» уровень из множества. Если долго поиграть, то можно заметить, что уровни повторяются. У них так же перма-смерть. 
Уникальность наших прохождений реализуется через покупку улучшений через магазин, случайность спавна врагов, случайности их сложности и прочего. Во многих играх примерно так же, но в них часто присутствуют, например, разные валюты, которые зарабатываются по-разному и открывают доступ к разному контенту. У нас же сейчас только один вид – за полное прохождение, поэтому фактический прогресс немного замедлен относительно других игр.

**Comment by SID37** [comment]
Ну, я прошёл игру, и мне дали одну монетку.. как-то от этого совсем грустно стало, я надеялся на несколько. Это надо 13 раз проходить на все улучшения (из них 4 раза без изменений потому что столько стоит самый дорогой апгрейд). В общем, гемплей ощущается слегка искусственно растянутым
